title:             A blog for Angel
email:             bohan9595@gmail.com
description:       Jesus | Puppy | Love | Doggy Date | Life
author:            Allan Chang
baseurl:           ""
url:               "https://www.angel.allan-chang.com"

# Social Profiles
twitter_username:  allan950404
github_username:   allan9595
facebook_username: profile.php?id=100007749556813

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
