title:             A blog for Angel
email:             bohan9595@gmail.com
description:       Jesus | Puppy | Love | Doggy Date | Life
author:            Allan Chang
baseurl:           ""
url:               "localhost:4000"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
